// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using static System.Net.WebRequestMethods;
using static NUnit.Framework.Constraints.Tolerance;
using JunquillalAutomatedTesting.PageObjectModels;


namespace JunquillalAutomatedTesting.Tests
{
    [TestFixture]

    public class TestFormularioLogin
    {

        private IWebDriver driver;
        private FormLoginPage paginLogin;

        public TestFormularioLogin()
        {
            driver = new ChromeDriver();
            paginLogin = new(driver);
        }

        public void SetUp()
        {
            driver.Navigate().GoToUrl("https://localhost:7042/Admin");
            driver.Manage().Window.Maximize();
        }

        public void TearDown()
        {
            driver.Quit();
        }


        [Test, Order(1)]
        public void inicioSesionManejoCredencialesVacios()
        {
            // Arrange
            SetUp();
            // Act
            paginLogin.PresionarBotonIniciarSesion();
            var mensajesError = paginLogin.ObtenerMensajesDeError();
            // Assert
            Assert.That(mensajesError[0].Text, Is.EqualTo("Por favor escriba su identificación"));
            Assert.That(mensajesError[1].Text, Is.EqualTo("Por favor escriba su contraseña"));
        }

        [Test, Order(2)]
        public void inicioSesionCredencialesErroneos()
        {
            // Arrange
            SetUp();
            // Act
            paginLogin.AgregarCredencialesDePrueba("usuario", "contrasena");
            paginLogin.PresionarBotonIniciarSesion();
            var mensajesError = paginLogin.ObtenerMensajesDeError();
            // Assert
            Assert.That(mensajesError[0].Text, Is.EqualTo("Escriba un ID valido"));
        }


        [Test, Order(3)]
        public void inicioSesionCredencialesCorrectos()
        {
            // Arrange
            SetUp();
            // Act
            paginLogin.AgregarCredencialesDePrueba("211118888", "1");
            paginLogin.PresionarBotonIniciarSesion();

            string urlActual = driver.Url;  // Obtener el URL actual de la página
            string urlEsperado = "https://localhost:7042/Admin/Home/Index";  // Obtener el URL actual de la página
            // Assert
            Assert.AreEqual(urlEsperado, urlActual, "El URL de la página no coincide con el esperado.");

            TearDown();

        }
    }
}